"""empty message

Revision ID: dde099ff89f0
Revises: 5832f3ca3bd7
Create Date: 2018-10-28 19:05:58.462694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dde099ff89f0'
down_revision = '5832f3ca3bd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Integer(), nullable=True),
    sa.Column('log', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['date'], ['animals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    #op.drop_table('spatial_ref_sys')
    op.add_column('analyses', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('analyses', sa.Column('longitude', sa.Float(), nullable=True))
    op.drop_index('idx_analyses_geom_mp', table_name='analyses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_analyses_geom_mp', 'analyses', ['geom_mp'], unique=False)
    op.drop_column('analyses', 'longitude')
    op.drop_column('analyses', 'latitude')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_table('logs')
    # ### end Alembic commands ###
